# Generated by Django 4.2.11 on 2026-05-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPLOAD_CREATED', 'Upload Created'), ('RECORD_CREATED', 'Record Created'), ('RECORD_UPDATED', 'Record Updated'), ('VALIDATION_RUN', 'Validation Run'), ('NORMALIZATION_RUN', 'Normalization Run'), ('REVIEW_ASSIGNED', 'Review Assigned'), ('RECORD_APPROVED', 'Record Approved'), ('RECORD_REJECTED', 'Record Rejected'), ('RECORD_ESCALATED', 'Record Escalated'), ('RECORD_LOCKED', 'Record Locked for Audit'), ('ANOMALY_FLAGGED', 'Anomaly Flagged'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('EXPORT_CREATED', 'Export Created')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='organizations.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_logs_organiz_86ff70_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['performed_by', '-created_at'], name='audit_logs_perform_d86b9a_idx')],
            },
        ),
    ]
