# Generated by Django 4.2.11 on 2026-05-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct Emissions'), ('SCOPE_2', 'Scope 2 — Indirect (Purchased Energy)'), ('SCOPE_3', 'Scope 3 — Value Chain')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('STATIONARY_COMBUSTION', 'Stationary Combustion'), ('MOBILE_COMBUSTION', 'Mobile Combustion'), ('FUGITIVE_EMISSIONS', 'Fugitive Emissions'), ('PURCHASED_ELECTRICITY', 'Purchased Electricity'), ('PURCHASED_HEAT', 'Purchased Heat & Steam'), ('BUSINESS_TRAVEL', 'Business Travel'), ('EMPLOYEE_COMMUTING', 'Employee Commuting'), ('UPSTREAM_TRANSPORT', 'Upstream Transportation'), ('WASTE_OPERATIONS', 'Waste in Operations'), ('FUEL_ENERGY', 'Fuel- and Energy-Related')], db_index=True, max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=6, help_text='Total CO₂e in kilograms', max_digits=20)),
                ('co2e_mt', models.DecimalField(blank=True, decimal_places=9, help_text='Total CO₂e in metric tons (auto-calculated)', max_digits=20, null=True)),
                ('source_data', models.JSONField(default=dict, help_text='Normalized source data snapshot')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('NORMALIZED', 'Normalized'), ('REVIEW_PENDING', 'Review Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED_FOR_AUDIT', 'Locked for Audit'), ('FAILED', 'Failed')], db_index=True, default='REVIEW_PENDING', max_length=30)),
                ('reporting_period_start', models.DateField(blank=True, db_index=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_emissions', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='organizations.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='organizations.organization')),
            ],
            options={
                'db_table': 'emission_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
