# Generated by Django 4.2.11 on 2026-05-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='upload_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.uploadsession'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='organizations.vendor'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope', '-created_at'], name='emission_re_organiz_f0d337_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'category', '-created_at'], name='emission_re_organiz_dfdc41_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['status', 'organization'], name='emission_re_status_d00545_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'reporting_period_start'], name='emission_re_organiz_548add_idx'),
        ),
    ]
