# Generated by Django 4.2.11 on 2026-05-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_reviews', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_reviews', to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='emissions.emissionrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_tasks', to='organizations.organization')),
            ],
            options={
                'db_table': 'review_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
                ('review_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='reviews.reviewtask')),
            ],
            options={
                'db_table': 'review_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['organization', 'decision'], name='review_task_organiz_2d0fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['assigned_to', 'decision'], name='review_task_assigne_74c0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['is_suspicious', 'decision'], name='review_task_is_susp_fa8cee_idx'),
        ),
    ]
