# Generated by Django 4.2.11 on 2026-05-28 08:46

import apps.ingestion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('emissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('CORPORATE_TRAVEL', 'Corporate Travel')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='organizations.organization')),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(max_length=1000, upload_to=apps.ingestion.models.upload_session_file_path)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('NORMALIZED', 'Normalized'), ('REVIEW_PENDING', 'Review Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED_FOR_AUDIT', 'Locked for Audit'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=30)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('passed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('warning_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='ingestion.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('normalized_data', models.JSONField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('suspicion_reasons', models.JSONField(default=list)),
                ('processing_notes', models.TextField(blank=True)),
                ('emission_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_record', to='emissions.emissionrecord')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.uploadsession')),
            ],
            options={
                'db_table': 'raw_records',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ValidationError',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='FAILED', max_length=20)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='ingestion.rawrecord')),
            ],
            options={
                'db_table': 'validation_errors',
                'ordering': ['severity', 'field_name'],
                'indexes': [models.Index(fields=['raw_record', 'severity'], name='validation__raw_rec_16b2cc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['organization', '-created_at'], name='upload_sess_organiz_0648fa_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status', 'organization'], name='upload_sess_status_a04dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['file_hash'], name='upload_sess_file_ha_0c4444_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['upload_session', 'validation_status'], name='raw_records_upload__40407b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['upload_session', 'is_suspicious'], name='raw_records_upload__9cc6c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('upload_session', 'row_number')},
        ),
    ]
